(function () {
  'use strict';
  const API = 'https://hatclaw.com/extencao';
  const KEY = 'hatclawLicense';
  const RELAY = 'browserKingRemoteBridge';
  const deviceKey = 'hatclawDeviceId';
  const get = (key) => chrome.storage.local.get(key).then((value) => value[key]);
  const set = (value) => chrome.storage.local.set({ [KEY]: value });
  const token = async () => { let value = String((await get(RELAY))?.token || '').trim(); if (!value) { try { const response = await chrome.runtime.sendMessage({ target: 'browserking-windows', action: 'relay.token', params: {} }); value = String(response?.result?.token || '').trim(); } catch (_) {} } return value; };
  const deviceId = async () => { let id = await get(deviceKey); if (!id) { id = `chrome-${crypto.randomUUID()}`; await chrome.storage.local.set({ [deviceKey]: id }); } return id; };
  async function request(path, options = {}) { const auth = await token(); const headers = new Headers(options.headers || {}); if (auth) headers.set('Authorization', `Bearer ${auth}`); headers.set('Content-Type', 'application/json'); const response = await fetch(`${API}${path}`, { ...options, headers }); const data = await response.json().catch(() => ({})); if (!response.ok) throw Error(data.error || `Falha de licença (${response.status})`); return data; }
  function render() { const overlay = document.createElement('div'); overlay.id = 'hatclaw-license-gate'; overlay.innerHTML = `<div class="license-card"><div class="license-brand">HATCLAW</div><h1>Ative sua extensão</h1><p>Insira o código de licença para liberar o agente neste dispositivo.</p><input id="license-code" placeholder="XXXX-XXXX-XXXX-XXXX" autocomplete="off"><button id="license-submit">Ativar extensão</button><small id="license-status"></small></div>`; const style = document.createElement('style'); style.textContent = '#hatclaw-license-gate{position:fixed;inset:0;z-index:2147483647;background:#080a08;display:grid;place-items:center;color:#eef7e9;font-family:system-ui,sans-serif}.license-card{width:min(420px,calc(100% - 32px));padding:32px;border:1px solid #36452b;border-radius:16px;background:#121810;box-shadow:0 20px 70px #000b}.license-brand{color:#c8ff3d;font:11px monospace;letter-spacing:.2em}.license-card h1{font-size:30px;margin:18px 0 8px}.license-card p{color:#9da89a;line-height:1.6}.license-card input,.license-card button{width:100%;padding:13px;border-radius:8px;font:inherit}.license-card input{margin:14px 0 10px;background:#0b0f0a;border:1px solid #34412c;color:#fff}.license-card button{background:#c8ff3d;color:#10140b;border:0;font-weight:700;cursor:pointer}.license-card small{display:block;margin-top:14px;color:#ff9d8c;min-height:20px}'; document.documentElement.append(style, overlay); return overlay; }
  async function validate(saved) { const data = await request('/licenses/validate', { method: 'POST', body: JSON.stringify({ deviceId: saved.deviceId }) }); return data.valid === true; }
  async function start() { const saved = await get(KEY); if (saved?.deviceId && saved?.license?.status === 'ACTIVE') { try { if (await validate(saved)) return true; } catch (_) {} } const overlay = render(); const status = overlay.querySelector('#license-status'); overlay.querySelector('#license-submit').onclick = async () => { const code = overlay.querySelector('#license-code').value.trim(); if (!code) return; status.textContent = 'Validando…'; try { const id = await deviceId(); const data = await request('/licenses/activate', { method: 'POST', body: JSON.stringify({ code, deviceId: id, extensionVersion: chrome.runtime.getManifest().version }) }); await set({ ...data, deviceId: id, validatedAt: Date.now() }); overlay.remove(); } catch (error) { status.textContent = error.message; } }; return false; }
  start().catch(() => render());
  setInterval(async () => { const saved = await get(KEY); if (!saved?.deviceId) return; try { if (!(await validate(saved))) { await chrome.storage.local.remove(KEY); location.reload(); } } catch (_) {} }, 15 * 60 * 1000);
})();
