plugins { id 'com.android.application' }

android {
    namespace 'com.browserking.remote'
    compileSdk 35

    defaultConfig {
        applicationId 'com.browserking.remote'
        minSdk 26
        targetSdk 35
        versionCode 5
        versionName '1.2.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
